#!/usr/bin/env bash
# install haproxy and configure loadbalancing
sudo apt-get update
sudo apt-get -y --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get -y install haproxy=1.8
printf "\nfrontend haproxynode
       bind *:80
       mode http
       default_backend backendnodes
backendnodes
       balance roundrobin
       server 1819-web-01 34.74.102.184:80 check
       server 1819-web-02 34.75.178.150:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
