#!/usr/bin/env bash
# echoes Holberton School x10 -4th intrtn "bad luck" 8th "good luck"

x=1
while [ $x -lt 10 ]
do
    ((x++))
    if [ $x -eq 4 ]
    then
	echo "bad luck"
    elif [ $x -eq 8 ]
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
done
