#!/usr/bin/env bash
# echoes Holberton School x10 -4th intrtn "bad luck" 8th "good luck"

x=1
while [ $x -le 8 ]
do
	echo "Holberton School"
	if [ $x -eq 3 ]
	then
		echo "bad luck"
	elif [ $x -eq 6 ]
	then
		echo "good luck"
	fi
	(( x++ ))
done
