#!/usr/bin/env bash
# Script that pkills apache2 and nginx and restarts them as user nginx

pkill -f apache2
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
